
name: CICD

on:
  push:
    branches: [ demos/main ]
  pull_request:
    branches: [ demos/main ]

env:
  ResourceGroupName: MyShuttle-${{ github.job }}
  SiteName: tspascoalmyshuttle-${{ github.job }}
  dbServerName: tspascoalmyshuttle-${{ github.job }}-mysql
  dbUser: dbuser
  artifactsName: artifacts

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package cobertura:cobertura --file pom.xml -DskipITs --batch-mode --quiet
      
    - uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        type: credscan,java
        
    - run: ls -al reports

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Tests Results
        files: '**/surefire-reports/TEST-*.xml'
        report_individual_runs: true
        deduplicate_classes_by_file_name: false

    - name: cobertura-report
      uses: 5monkeys/cobertura-action@v6
      if: github.event_name == 'pull_request' && always()
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        path: '**/coverage.xml'
        minimum_coverage: 5

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        path: |
            **/target/*.war 
            *.sql 
            IaC/**/*.*
        name: ${{ env.artifactsName }}
