
name: CICD

on:
  push:
    branches: [ demos/main ]
  pull_request:
    branches: [ demos/main ]

jobs:
      
  container:
    name: container scanning
    
    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package cobertura:cobertura --file pom.xml -DskipITs --batch-mode --quiet

      - name: Build an image from Dockerfile
        run: |
          docker build -t ghcr.io/myshuttle:${{ github.sha }} . -f src/Dockerfile

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/myshuttle:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - uses: actions/upload-artifact@v1
        with:
          path: 'trivy-results.sarif'
          name: trivy

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
          
      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        id: anchore-scan
        uses: anchore/scan-action@v3
        with:
          image: "ghcr.io/myshuttle:${{ github.sha }}"
          acs-report-enable: true
          fail-build: false
          severity-cutoff: low
          
      - uses: actions/upload-artifact@v1
        with:
          path: '${{ steps.anchore-scan.outputs.sarif }}'
          name: anchore

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.anchore-scan.outputs.sarif }}
          


